### ISSUE TITLE
TypeError: _map_state_dict_to_module() missing 1 required positional argument: 'prefix'

### ISSUE THREAD

**Issue by HuangCongQing** [CVMI-Lab/SparseKD#3]
![image](https://user-images.githubusercontent.com/20675770/210789136-615dda0a-1dd0-4133-b45e-55fca4986a67.png)

I modified this `ENABLED` parameter to True
```
    REMAP_PRETRAIN: #
        ENABLED: True # False  True!!!!
        WAY: BN_SCALE # 重映射方式
        BN_SCALE:
            ABS: True # 参数
        OFA:
            l1_norm: max
```

When I run the code, I get an error. How shall I approach this problom?Thx.
```
python train.py --cfg_file=cfgs/waymo_models/cp-pillar/cp-pillar-v0.4_sparsekd.yaml  --batch_size=4 --epochs=20
```
