### ISSUE TITLE
Where are these 0.5, 0.75 distillation parameters configured?

### ISSUE THREAD

**Issue by HuangCongQing** [CVMI-Lab/SparseKD#4]
![image](https://user-images.githubusercontent.com/20675770/211277442-cda99feb-6f72-4a93-a131-3c3d0f4a0123.png)

Is there a separate distillation ratio(0.5, 0.75) configuration parameter? Or do I just change channle to featuremap? The following code

```
    VFE:
        NAME: PillarVFE
        WITH_DISTANCE: False
        USE_ABSLOTE_XYZ: True
        USE_NORM: True
        NUM_FILTERS: [ 64, 64 ] # --->>> NUM_FILTERS: [ 32, 32 ] That's the only way to change it?
```
